import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTitle } from '@/hooks/use-title';

export default function TermsOfService() {
  useTitle('Terms of Service');

  return (
    <div className="min-h-screen bg-background py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Button variant="ghost" asChild className="mb-8 hover:bg-muted -ml-4">
            <Link to="/"><ArrowLeft className="w-4 h-4 mr-2"/> Back to Home</Link>
        </Button>

        <div className="bg-card rounded-2xl shadow-sm border border-border p-8 sm:p-12">
          <h1 className="text-3xl font-extrabold text-foreground mb-8">Terms of Service</h1>
          
          <div className="text-muted-foreground">
            <p className="mb-6 font-medium text-foreground">Last updated: {new Date().toLocaleDateString()}</p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">1. Acceptance of Terms</h3>
            <p className="mb-4 leading-relaxed">
              By accessing and using GreenSteps ("we," "our," or "us"), you agree to comply with and be bound by these Terms of Service. If you do not agree, please do not use our services.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">2. Description of Service</h3>
            <p className="mb-4 leading-relaxed">
              GreenSteps provides AI-powered sustainability coaching, impact tracking, and material analysis tools. Our services rely on advanced artificial intelligence models, including Google Gemini, to generate content and recommendations.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">3. AI-Generated Content</h3>
            <p className="mb-4 leading-relaxed">
              Much of the content and advice provided on GreenSteps is generated by artificial intelligence. While we strive for accuracy, AI models can make mistakes ("hallucinations"). You acknowledge that:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>We do not guarantee the accuracy, completeness, or safety of any AI-generated advice.</li>
              <li>You should use professional judgment and verify critical information independently.</li>
              <li>We are not liable for actions taken based on AI recommendations.</li>
            </ul>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">4. User Conduct</h3>
            <p className="mb-4 leading-relaxed">
              You agree not to use our services for any unlawful purpose, to harass others, or to input malicious data. We reserve the right to terminate accounts that violate these standards.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">5. Third-Party Services</h3>
            <p className="mb-4 leading-relaxed">
              Our application integrates with third-party services, including Google Gemini API. Your use of our voice coach and AI generation tools is also subject to <a href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-medium">Google's Terms of Service</a>.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">6. Limitation of Liability</h3>
            <p className="mb-4 leading-relaxed">
              To the fullest extent permitted by law, GreenSteps shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4 text-foreground">7. Changes to Terms</h3>
            <p className="mb-4 leading-relaxed">
              We may update these terms at any time. Continued use of the service constitutes acceptance of the new terms.
            </p>

            <div className="mt-12 pt-8 border-t border-border">
              <p className="text-sm">
                Questions? Contact us at <a href="mailto:mhd12@devlix.org" className="text-primary hover:underline font-medium">mhd12@devlix.org</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
