import uuid
from sqlalchemy import Column, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from core.database import Base


class Material(Base):
    __tablename__ = "materials"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Editable by user (only field you allow to edit later)
    title = Column(String, nullable=False)

    # Generated by Gemini from the user image
    description = Column(Text, nullable=True)

    owner_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    created_at = Column(DateTime, server_default=func.now())

    # Delete material => delete all ways too
    ways = relationship("MaterialWay", back_populates="material", cascade="all, delete-orphan")